name: ReadTracker Issue (RT)
description: Create an issue for the ReadTracker app
title: "RT: [Issue Title]"
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Bug
        - Enhancement
        - Documentation
        - Question
        - Feature Request
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and detailed description of the issue
      placeholder: Describe the issue, what you expected to happen, and what actually happened...
    validations:
      required: true
